{
  "hash": "b4baa7cb291d86499bbb0b10c73ca0f6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Post 3: Hypothesis Test Comparing Mean Age Across Workclass Groups\"\nauthor: \"Mia Harrison\"\ndate: \"2026-04-23\"\ncategories: [Inference, Permutation Test, Adult Income Data]\nformat:\n  html:\n    code-fold: true\n    toc: true\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n## Introduction\n\nFor this analysis, I use the Adult Income dataset, a census-based dataset containing demographic and employment information for individual adults. Each row in the dataset represents one person. I focus on whether average age differs between two workclass groups: individuals working in the private sector and individuals who are self-employed but not incorporated. The dataset used here contains more than 40,000 observations, and after filtering to these two workclass categories, the sample still includes a large number of individuals in both groups.\n\n## Data\n\nThe dataset used in this analysis comes from the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/adult)\n\nMy research question is: **Do individuals working in the private sector differ in average age from individuals who are self-employed but not incorporated?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(infer)\ndf <- read_csv(\"train.csv\")\ndf_clean <- df %>%\n  filter(workclass %in% c(\"Private\", \"Self-emp-not-inc\"))\n```\n:::\n\n\n\n## Exploratory Comparison\n\nBefore conducting a formal hypothesis test, I first compare the age distributions of the two groups visually and numerically. The boxplot below shows the distribution of age for workers in the private sector and those who are self-employed but not incorporated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df_clean, aes(x = workclass, y = age)) +\n  geom_boxplot() +\n  labs(\n    title = \"Age Distribution by Workclass\",\n    x = \"Workclass\",\n    y = \"Age (years)\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe boxplot suggests that self-employed individuals tend to be older than those working in the private sector. The median age is clearly higher for the self-employed group, although there is still overlap between the two distributions. There are also several older outliers in both groups.\n\nTo compare the group means directly, I calculate the mean age for each group below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_means <- df_clean %>%\n  group_by(workclass) %>%\n  summarize(\n    mean_age = mean(age),\n    n = n()\n  )\n\ngroup_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  workclass        mean_age     n\n  <chr>               <dbl> <int>\n1 Private              36.9 30587\n2 Self-emp-not-inc     45.4  3464\n```\n\n\n:::\n:::\n\n\nThe average age in the private sector is lower than the average age among self-employed individuals. This suggests a noticeable difference, but a hypothesis test is needed to determine whether that difference is statistically significant.\n\n## Bootstrap Confidence Intervals\n\nTo better understand the uncertainty around each group mean, I construct separate bootstrap confidence intervals for the mean age of each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprivate_boot <- df_clean %>%\n  filter(workclass == \"Private\") %>%\n  specify(response = age) %>%\n  generate(reps = 1000, type = \"bootstrap\") %>%\n  calculate(stat = \"mean\")\n\nself_boot <- df_clean %>%\n  filter(workclass == \"Self-emp-not-inc\") %>%\n  specify(response = age) %>%\n  generate(reps = 1000, type = \"bootstrap\") %>%\n  calculate(stat = \"mean\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprivate_ci <- quantile(private_boot$stat, c(0.025, 0.975))\nself_ci <- quantile(self_boot$stat, c(0.025, 0.975))\n\nci_summary <- tibble(\n  workclass = c(\"Private\", \"Self-emp-not-inc\"),\n  mean_age = c(\n    mean(df_clean$age[df_clean$workclass == \"Private\"]),\n    mean(df_clean$age[df_clean$workclass == \"Self-emp-not-inc\"])\n  ),\n  lower = c(private_ci[1], self_ci[1]),\n  upper = c(private_ci[2], self_ci[2])\n)\n\nci_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  workclass        mean_age lower upper\n  <chr>               <dbl> <dbl> <dbl>\n1 Private              36.9  36.7  37.0\n2 Self-emp-not-inc     45.4  44.9  45.9\n```\n\n\n:::\n:::\n\n\nThe table above gives the observed mean age for each group along with the lower and upper bounds of the 95% bootstrap confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ci_summary, aes(x = workclass, y = mean_age)) +\n  geom_col() +\n  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +\n  labs(\n    title = \"Bootstrap Confidence Intervals for Mean Age\",\n    x = \"Workclass\",\n    y = \"Mean Age\",\n    caption = \"Source: Adult Income Dataset\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe confidence intervals provide a visual summary of uncertainty around each mean. In this case, the intervals show that the self-employed group has a higher average age than the private-sector group. If the intervals do not overlap much, that is a strong visual clue that the groups differ.\n\n## Hypotheses\n\nTo formally test whether mean age differs between the two groups, I use a permutation test.\n\nLet group 1 be **Private** and group 2 be **Self-emp-not-inc**.\n\nThe null hypothesis is:\n\nH0:μPrivate−μSelf-emp-not-inc=0H0​:μPrivate​−μSelf-emp-not-inc​=0\n\nThis means that the average age is the same in both groups.\n\nThe alternative hypothesis is:\n\nHA:μPrivate−μSelf-emp-not-inc≠0HA​:μPrivate​−μSelf-emp-not-inc​=0\n\nThis is a two-sided alternative because I want to test whether the two groups differ, without assuming in advance which one must be older.\n\n## Null Distribution and P-value\n\nTo test the null hypothesis, I generate a null distribution by permuting workclass labels and recalculating the difference in mean age many times.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist <- df_clean %>%\n  specify(response = age, explanatory = workclass) %>%\n  hypothesize(null = \"independence\") %>%\n  generate(reps = 1000, type = \"permute\") %>%\n  calculate(stat = \"diff in means\", order = c(\"Private\", \"Self-emp-not-inc\"))\n\nobs_stat <- df_clean %>%\n  specify(response = age, explanatory = workclass) %>%\n  calculate(stat = \"diff in means\", order = c(\"Private\", \"Self-emp-not-inc\"))\n\nobs_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: age (numeric)\nExplanatory: workclass (factor)\n# A tibble: 1 × 1\n   stat\n  <dbl>\n1 -8.54\n```\n\n\n:::\n:::\n\n\nThe observed statistic above is the difference in mean age between the private-sector group and the self-employed group. Because the order is `Private - Self-emp-not-inc`, a negative value means that private-sector workers are younger on average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value <- get_p_value(null_dist, obs_stat = obs_stat, direction = \"two-sided\")\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1       0\n```\n\n\n:::\n:::\n\n\nThe p-value is essentially 0, which means that none of the 1,000 simulated differences under the null hypothesis were as extreme as the observed difference. In practice, this should be interpreted as **p \\< 0.001**, not as a literal probability of zero.\n\n## Visualizing the P-value\n\nThe plot below shows the null distribution of differences in mean age under the assumption that workclass and age are unrelated. The shaded region highlights simulated values at least as extreme as the observed difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisualize(null_dist) +\n  shade_p_value(obs_stat = obs_stat, direction = \"two-sided\") +\n  labs(\n    title = \"Null Distribution of the Difference in Mean Age\",\n    x = \"Difference in Means\",\n    y = \"Count\",\n    caption = \"Source: Adult Income Dataset\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe null distribution is centered near 0, which is what we would expect if the two groups truly had the same average age. The observed difference falls far from the center of this distribution, and the shaded area is extremely small. This indicates that the observed difference would be very unlikely if the null hypothesis were true.\n\n## Decision\n\nFor this analysis, I use a significance level of α=0.05, which is a standard threshold in statistical testing.\n\nBecause the p-value is far below 0.05, I reject the null hypothesis. There is strong statistical evidence that average age differs between individuals working in the private sector and those who are self-employed but not incorporated.\n\n## Practical Significance\n\nStatistical significance does not automatically mean the difference is important in practice, so it is useful to consider the size of the effect. In this dataset, the average age for private-sector workers is about 36.9 years, while the average age for self-employed workers is about 45.4 years. This is a difference of roughly 8.5 years, which is substantial in real-world terms.\n\nThis difference may reflect differences in career paths. Self-employment may be more common among older adults who have accumulated more work experience, resources, or professional independence over time. That means age differences between these groups may not be caused by workclass itself, but instead may reflect broader life-cycle and labor-market patterns.\n\n## Conclusion\n\nIn this post, I examined whether average age differs between private-sector workers and self-employed workers in the Adult Income dataset. The exploratory boxplot, the group means, the bootstrap confidence intervals, and the permutation test all point to the same conclusion: self-employed individuals in this sample are older on average than private-sector workers. The p-value was extremely small, providing strong evidence against the null hypothesis of no difference. The observed gap of about 8.5 years is also practically meaningful, although the comparison should be interpreted carefully because these groups may differ in other ways beyond workclass alone.\n",
    "supporting": [
      "../../index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}